# Generated by Django 5.0 on 2025-12-12 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banner',
            new_name='Promo',
        ),
        migrations.AlterModelOptions(
            name='promo',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Промоция', 'verbose_name_plural': 'Промоции'},
        ),
    ]
