# Generated by Django 5.0 on 2025-12-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_banner_promo_alter_promo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='image',
            field=models.ImageField(upload_to='hero/', verbose_name='Изображение'),
        ),
    ]
